#ifndef PLATFORMIEEEEUI64_H
#define PLATFORMIEEEEUI64_H

enum {
  IEEE_EUI64_COMPANY_ID_0 = 0xC0, // University of Michigan
  IEEE_EUI64_COMPANY_ID_1 = 0x98,
  IEEE_EUI64_COMPANY_ID_2 = 0xE5,
  IEEE_EUI64_SERIAL_ID_0 = 'C',
  IEEE_EUI64_SERIAL_ID_1 = 'O',
};

#endif
