COMPONENT=RpiCalibrateAllIpC

PFLAGS += -DCC2420_DEF_CHANNEL=18
PFLAGS += -DCC2520_DEF_CHANNEL=18

PFLAGS += -DIN6_PREFIX="\"fec0\""

PFLAGS += "-I../CCPowerMeterIp/"
PFLAGS += "-I../RpiCalibrateCCIp/"

TINYOS_ROOT_DIR?=../..
include $(TINYOS_ROOT_DIR)/Makefile.include
